name: Sync LeetCode

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install script dependencies
        working-directory: scripts
        run: npm install --no-audit --no-fund

      - name: Sync LeetCode submissions
        working-directory: scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        run: node sync-leetcode.js
